name: Python Lint and Type Check

on:
  push:
#    branches:
#      - 'feature/*'
#      - 'main'
    paths:
      - '**.py'

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy

      - name: Lint and type check
        run: |
          find . -name "*.py" -exec flake8 {} +
#          find . -name "*.py" -exec mypy --ignore-missing-imports {} +
