name: python lint checker

on:
  pull_request:
  push:
    paths:
      - '**.py'

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ricardochaves/python-lint@v1.4.0
