name: Python Linting and Type Checking

on: [push, pull_request]

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy

    - name: Run flake8
      run: |
        flake8

    - name: Run mypy
      run: |
        mypy
